from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.pdfbase.pdfmetrics import stringWidth

from datetime import datetime


def generate_pdf(resume_result, ats_result):

    filename = "AI_Resume_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    # -----------------------------
    # Custom Styles
    # -----------------------------

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.textColor = HexColor("#1F4E79")

    heading_style = styles["Heading1"]
    heading_style.textColor = HexColor("#0B5394")

    body_style = styles["BodyText"]
    body_style.leading = 22

    story = []

    # -----------------------------
    # Cover Page
    # -----------------------------

    story.append(
        Paragraph(
            "AI Resume Analysis Report",
            title_style
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<b>Generated using</b><br/>"
            "LangChain + Gemini + FAISS + Streamlit",
            body_style
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            body_style
        )
    )

    story.append(Spacer(1, 40))

    story.append(
        Paragraph(
            "This report was automatically generated by the AI Resume Analyzer.",
            body_style
        )
    )

    story.append(PageBreak())

    # -----------------------------
    # Resume Analysis
    # -----------------------------

    story.append(
        Paragraph(
            "Resume Analysis",
            heading_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            resume_result.replace("\n", "<br/>"),
            body_style
        )
    )

    story.append(PageBreak())

    # -----------------------------
    # ATS Report
    # -----------------------------

    story.append(
        Paragraph(
            "ATS Resume Analysis",
            heading_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            ats_result.replace("\n", "<br/>"),
            body_style
        )
    )

    story.append(Spacer(1, 30))

    # -----------------------------
    # Footer
    # -----------------------------

    story.append(
        Paragraph(
            "<b>Thank You!</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            "Generated by AI Resume Analyzer developed by Rushikesh Panchal.",
            body_style
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "Powered by LangChain | Google Gemini | FAISS | HuggingFace Embeddings | Streamlit",
            body_style
        )
    )

    doc.build(story)

    return filename